#!/usr/bin/env bash
# copies file to a server wih scp
if [ $# -lt 3 ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
fi
file_path=$1
ip=$2
user=$3
ssh_key=$4
scp "$file_path" -i "$ssh_key" -T "$user@$ip:~/"
