#!/usr/bin/env bash
# configure an nginx server return a page by default
apt update
apt install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
curl localhost
