#!/usr/bin/env bash
# configure an nginx server return a page by default
apt-get update
apt-get -y install nginx

yes | ufw allow 'Nginx HTTP'
yes | ufw enable

sudo service nginx start

echo 'Hello World!' > /var/www/html/index.html
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default

sudo service nginx reload
