#!/usr/bin/env bash
# configures a url redirect at /redirect_me
sed -i -r 's/^(\s+)(# SSL configuration)/\1rewrite \^\/redirect_me\[\/\]*\$ https:\/\/google.com permanent\;\n\1\2/g' /etc/nginx/sites-available/default
systemctl restart nginx
