#!/usr/bin/env bash
# configures a url redirect at /redirect_me
apt-get update
apt-get -y install nginx

yes | ufw allow 'Nginx HTTP'
yes | ufw enable
service nginx start

line=$(grep -Eno "^\s*listen \[::\]:80 default_server;" /etc/nginx/sites-available/default | cut -d : -f 1)
sed -i "$line a\ \trewrite ^/redirect_me[/]*$ https:\/\/google.com permanent;" /etc/nginx/sites-available/default

service nginx reload
