#!/usr/bin/env bash
# configures a custom error 404 page
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw enable
service nginx start
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i -r 's/^(\s+)(# SSL configuration)/\1error_page 404 \/error404\.html\;\n\1\2/g' /etc/nginx/sites-available/default
service nginx reload
