#!/usr/bin/env bash
# configures a custom error 404 page
apt-get update
apt-get -y install nginx

yes | ufw allow 'Nginx HTTP'
yes | ufw enable

service nginx start

echo "Ceci n'est pas une page" > /var/www/html/error404.html
line=$(grep -Eno "^\s*listen \[::\]:80 default_server;" /etc/nginx/sites-available/default | cut -d : -f 1)
    sed -i "$line a\ \terror_page 404 /error404.html;" /etc/nginx/sites-available/default

service nginx reload
