#!/usr/bin/env bash
# configures a custom http header
# ignore SC2154
apt-get update
apt-get -y install nginx
yes | ufw allow 'Nginx HTTP'
yes | ufw enable
lsof -t -i tcp:80 | xargs kill
service nginx start

line=$( grep -Eno "^\s*location / {" /etc/nginx/sites-available/default | cut -d : -f 1)

sed -i "$line a\ \t\tadd_header X-Served-By $HOSTNAME always\;" /etc/nginx/sites-available/default

service nginx reload
