#!/usr/bin/env bash
# configures a custom http header
# ignore SC2154
apt-get update
apt-get -y install nginx
yes | ufw allow 'Nginx HTTP'
yes | ufw enable
lsof -t -i tcp:80 | xargs kill
service nginx start

LINE=$( grep -Eno "^\s*listen \[::\]:80 default_server;" /etc/nginx/sites-available/default | cut -d : -f 1)

EXIST=$(grep -Eco "^\s*location /hbnb_static {" /etc/nginx/sites-available/default)

if [ "$EXIST" -le 0 ]
then
    sed -i "$LINE a\ \tadd_header X-Served-By $HOSTNAME always\;" /etc/nginx/sites-available/default
fi

service nginx reload
