#!/usr/bin/env bash
# fix the nginx not starting error
sudo sed -Ei -e "s|8080|80|g" /etc/nginx/sites-enabled/default
sudo sed -Ei -e "s|8080|80|g" /etc/nginx/sites-available/default
sudo service nginx restart
