#!/usr/bin/env bash
# fix the nginx not starting error
sudo apt-get install -y --no-upgrade psmisc
sudo fuser -k 80/tcp

listen=$(grep -Eco "^\s*listen 80 default_server;" /etc/nginx/sites-available/default)

if [ "$listen" -eq 0 ]
then
    sudo sed -Ei "/^\s*server {/ a\ \tlisten 80 default_server;" /etc/nginx/sites-available/default
fi

sudo service nginx start
sudo service nginx reload
