#!/usr/bin/env bash
# runs nginx as user nginx
chmod 666 /etc/nginx/nginx.conf
sed -i "1 i\ user nginx" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
service nginx stop
sudo -u nginx service nginx start
